version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/config
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/ui
    schedule:
      interval: daily
